services:
  runner:
    build: &runner-build
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
      target: runner
      tags:
        - ghcr.io/matthewbaggett/act-runner:latest
    image: ghcr.io/matthewbaggett/act-runner:latest
  embedded-runner:
    build:
      <<: *runner-build
      target: embedded-runner
      tags:
        - ghcr.io/matthewbaggett/act-runner:embedded
    image: ghcr.io/matthewbaggett/act-runner:embedded
